[config]
schemaVersion = "0.0.1"

[package]
namespace = "bo0tzz"
name = "EndlessPeglin"
versionNumber = "1.2.1"
description = "Start new games with your orbs and relics from the previous run."
websiteUrl = "https://github.com/bo0tzz/EndlessPeglin"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.1900"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []